"""Auto-generated by Detective — warrant-classed tests for src/model_atlas/query_navigate.py::render_question."""

import pytest
from model_atlas.query_navigate import render_question


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (
            (
                "splitting_anchor",
                {"present_in": 3, "out_of": 8, "anchor": "tool-calling"},
            ),
            "3 of the 8 carry tool-calling, the rest don't. Shall I insist on it?",
        ),
        (
            (
                "unconstrained_axis",
                {
                    "range_low": "-2",
                    "range_high": "+3",
                    "bank": "EFFICIENCY",
                    "answer_low": "smaller",
                    "answer_high": "larger",
                },
            ),
            "These range from -2 to +3 on EFFICIENCY, which is rather a wide field. Would you prefer smaller, or larger?",
        ),
    ],
)
def test_render_question_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert render_question(*args) == expected


@pytest.mark.detective
def test_render_question_value_0():
    """VALUE survivor — distinguishing witness (original raises KeyError: "template 'unconstrained_axis' needs slot 'range_high'") (confidence 0.95)."""
    try:
        _result = render_question("unconstrained_axis", {"range_low": "-2"})
    except KeyError as _exc:
        assert str(_exc) == "\"template 'unconstrained_axis' needs slot 'range_high'\""
    except BaseException as _exc:
        pytest.fail(f"expected KeyError, got {type(_exc).__name__}: {_exc!r}")
    else:
        pytest.fail(f"expected KeyError, but the call returned {_result!r}")
