"""Bootstrap anchor dictionary for the semantic network.

Initial vocabulary across all 8 semantic banks, seeded into the anchors
table on first init_db() call.
"""

from __future__ import annotations

BOOTSTRAP_ANCHORS: list[tuple[str, str, str]] = [
    # ARCHITECTURE
    ("transformer", "ARCHITECTURE", "type"),
    ("encoder-only", "ARCHITECTURE", "type"),
    ("encoder-decoder", "ARCHITECTURE", "type"),
    ("decoder-only", "ARCHITECTURE", "type"),
    ("mixture-of-experts", "ARCHITECTURE", "type"),
    ("mamba", "ARCHITECTURE", "type"),
    ("rwkv", "ARCHITECTURE", "type"),
    ("ssm", "ARCHITECTURE", "type"),
    ("hybrid", "ARCHITECTURE", "type"),
    ("diffusion", "ARCHITECTURE", "type"),
    ("vision-transformer", "ARCHITECTURE", "type"),
    ("grouped-query-attention", "ARCHITECTURE", "attention"),
    ("rope-linear", "ARCHITECTURE", "positional-encoding"),
    ("rope-dynamic", "ARCHITECTURE", "positional-encoding"),
    ("rope-yarn", "ARCHITECTURE", "positional-encoding"),
    ("rope-longrope", "ARCHITECTURE", "positional-encoding"),
    # CAPABILITY
    ("instruction-following", "CAPABILITY", "training"),
    ("chat", "CAPABILITY", "training"),
    ("tool-calling", "CAPABILITY", "skill"),
    ("function-calling", "CAPABILITY", "skill"),
    ("code-generation", "CAPABILITY", "skill"),
    ("code-completion", "CAPABILITY", "skill"),
    ("creative-writing", "CAPABILITY", "skill"),
    ("reasoning", "CAPABILITY", "skill"),
    ("math", "CAPABILITY", "skill"),
    ("NER", "CAPABILITY", "skill"),
    ("orchestration", "CAPABILITY", "skill"),
    ("structured-output", "CAPABILITY", "skill"),
    ("embedding", "CAPABILITY", "skill"),
    ("classification", "CAPABILITY", "skill"),
    ("translation", "CAPABILITY", "skill"),
    ("summarization", "CAPABILITY", "skill"),
    ("question-answering", "CAPABILITY", "skill"),
    ("image-generation", "CAPABILITY", "skill"),
    ("image-understanding", "CAPABILITY", "skill"),
    ("multimodal", "CAPABILITY", "skill"),
    ("time-series", "CAPABILITY", "skill"),
    ("long-context", "CAPABILITY", "feature"),
    ("schema-following", "CAPABILITY", "skill"),
    ("constrained-generation", "CAPABILITY", "skill"),
    ("proof-level-math", "CAPABILITY", "skill"),
    ("olympiad-math", "CAPABILITY", "skill"),
    # EFFICIENCY
    ("sub-1B", "EFFICIENCY", "size"),
    ("1B-class", "EFFICIENCY", "size"),
    ("3B-class", "EFFICIENCY", "size"),
    ("7B-class", "EFFICIENCY", "size"),
    ("13B-class", "EFFICIENCY", "size"),
    ("30B-class", "EFFICIENCY", "size"),
    ("70B-class", "EFFICIENCY", "size"),
    ("frontier-class", "EFFICIENCY", "size"),
    ("consumer-GPU-viable", "EFFICIENCY", "hardware"),
    ("edge-deployable", "EFFICIENCY", "hardware"),
    ("quantized", "EFFICIENCY", "optimization"),
    ("gptq-quantized", "EFFICIENCY", "quantization"),
    ("awq-quantized", "EFFICIENCY", "quantization"),
    ("bnb-quantized", "EFFICIENCY", "quantization"),
    ("long-context-32k", "EFFICIENCY", "context"),
    ("long-context-128k", "EFFICIENCY", "context"),
    ("long-context-1m", "EFFICIENCY", "context"),
    # COMPATIBILITY
    ("GGUF-available", "COMPATIBILITY", "format"),
    ("GPTQ-available", "COMPATIBILITY", "format"),
    ("AWQ-available", "COMPATIBILITY", "format"),
    ("EXL2-available", "COMPATIBILITY", "format"),
    ("safetensors", "COMPATIBILITY", "format"),
    ("ONNX-available", "COMPATIBILITY", "format"),
    ("Apple-Silicon-native", "COMPATIBILITY", "hardware"),
    ("CPU-inference", "COMPATIBILITY", "hardware"),
    ("OpenVINO", "COMPATIBILITY", "framework"),
    ("CoreML", "COMPATIBILITY", "framework"),
    ("TFLite", "COMPATIBILITY", "framework"),
    ("MLX-compatible", "COMPATIBILITY", "framework"),
    ("llama-cpp-compatible", "COMPATIBILITY", "framework"),
    ("vLLM-compatible", "COMPATIBILITY", "framework"),
    ("TensorRT-compatible", "COMPATIBILITY", "framework"),
    ("transformers-compatible", "COMPATIBILITY", "framework"),
    ("diffusers-compatible", "COMPATIBILITY", "framework"),
    ("chat-template-available", "COMPATIBILITY", "feature"),
    ("commercial-use-allowed", "COMPATIBILITY", "license"),
    ("research-only", "COMPATIBILITY", "license"),
    ("llama-license", "COMPATIBILITY", "license"),
    # LINEAGE
    ("Llama-family", "LINEAGE", "family"),
    ("Mistral-family", "LINEAGE", "family"),
    ("Qwen-family", "LINEAGE", "family"),
    ("Phi-family", "LINEAGE", "family"),
    ("Gemma-family", "LINEAGE", "family"),
    ("GPT-family", "LINEAGE", "family"),
    ("Falcon-family", "LINEAGE", "family"),
    ("StableLM-family", "LINEAGE", "family"),
    ("DeepSeek-family", "LINEAGE", "family"),
    ("Yi-family", "LINEAGE", "family"),
    ("Command-family", "LINEAGE", "family"),
    ("base-model", "LINEAGE", "role"),
    ("fine-tune", "LINEAGE", "role"),
    ("merge", "LINEAGE", "role"),
    ("distillation", "LINEAGE", "role"),
    # DOMAIN
    ("code-domain", "DOMAIN", "broad"),
    ("science-domain", "DOMAIN", "broad"),
    ("medical-domain", "DOMAIN", "broad"),
    ("legal-domain", "DOMAIN", "broad"),
    ("finance-domain", "DOMAIN", "broad"),
    ("multilingual", "DOMAIN", "broad"),
    ("creative-domain", "DOMAIN", "broad"),
    ("math-domain", "DOMAIN", "broad"),
    ("Python-code", "DOMAIN", "language"),
    ("Rust-code", "DOMAIN", "language"),
    ("C++-code", "DOMAIN", "language"),
    ("JavaScript-code", "DOMAIN", "language"),
    ("TypeScript-code", "DOMAIN", "language"),
    ("Go-code", "DOMAIN", "language"),
    ("Java-code", "DOMAIN", "language"),
    ("systems-programming", "DOMAIN", "specialization"),
    ("web-development", "DOMAIN", "specialization"),
    ("proof-assistant", "DOMAIN", "specialization"),
    ("formal-verification", "DOMAIN", "specialization"),
    # QUALITY
    ("trending", "QUALITY", "signal"),
    ("high-downloads", "QUALITY", "signal"),
    ("community-favorite", "QUALITY", "signal"),
    ("official-release", "QUALITY", "signal"),
    ("experimental", "QUALITY", "signal"),
    ("deprecated", "QUALITY", "signal"),
    ("high-mmlu", "QUALITY", "benchmark"),
    ("strong-humaneval", "QUALITY", "benchmark"),
    ("strong-gsm8k", "QUALITY", "benchmark"),
    ("safety-tested", "QUALITY", "benchmark"),
    ("red-teamed", "QUALITY", "benchmark"),
    # TRAINING
    ("sft-trained", "TRAINING", "method"),
    ("rlhf-trained", "TRAINING", "method"),
    ("dpo-trained", "TRAINING", "method"),
    ("ppo-trained", "TRAINING", "method"),
    ("orpo-trained", "TRAINING", "method"),
    ("kto-trained", "TRAINING", "method"),
    ("lora-adapted", "TRAINING", "method"),
    ("qlora-adapted", "TRAINING", "method"),
    ("adapter-tuned", "TRAINING", "method"),
    ("distilled", "TRAINING", "method"),
    ("quantization-aware-trained", "TRAINING", "method"),
    ("trained-on-synthetic-data", "TRAINING", "data"),
    ("trained-on-human-feedback", "TRAINING", "data"),
    ("multi-stage-alignment", "TRAINING", "process"),
    ("curriculum-trained", "TRAINING", "process"),
    ("continual-pretrained", "TRAINING", "process"),
]
