"""C4: Ground truth validation against reference datasets.

Compares ModelAtlas extraction outputs against two curated ground truth
datasets from davanstrien:

- hub-tldr-model-summaries-llama: ~5K model summaries generated by Llama 3.3 70B
- parsed-model-cards: ~5K structured extractions by QwQ-32B

No LLM needed — runs offline using string similarity and field comparison.
"""

from __future__ import annotations

import difflib
import logging
import sqlite3

logger = logging.getLogger(__name__)


def load_hub_tldr_summaries() -> dict[str, str]:
    """Load ~5K reference summaries from davanstrien/hub-tldr-model-summaries-llama.

    Returns dict mapping model_id -> reference summary string.
    Requires the `datasets` package.
    """
    from datasets import load_dataset

    ds = load_dataset("davanstrien/hub-tldr-model-summaries-llama", split="train")
    result: dict[str, str] = {}
    for row in ds:
        model_id = row.get("repo_id") or row.get("model_id") or ""
        summary = row.get("summary") or row.get("text") or ""
        if model_id and summary:
            result[model_id] = summary
    logger.info(
        "Loaded %d reference summaries from hub-tldr-model-summaries-llama", len(result)
    )
    return result


def load_parsed_model_cards() -> dict[str, dict]:
    """Load ~5K structured extractions from davanstrien/parsed-model-cards.

    Returns dict mapping model_id -> parsed fields dict.
    Requires the `datasets` package.
    """
    from datasets import load_dataset

    ds = load_dataset("davanstrien/parsed-model-cards", split="train")
    result: dict[str, dict] = {}
    for row in ds:
        model_id = row.get("repo_id") or row.get("model_id") or ""
        if model_id:
            result[model_id] = dict(row)
    logger.info("Loaded %d parsed model cards from parsed-model-cards", len(result))
    return result


def _compare_summaries(
    network_conn: sqlite3.Connection,
    gt_summaries: dict[str, str],
) -> tuple[list[float], list[dict]]:
    """Compare our summaries against ground truth reference summaries.

    Returns (similarities, flagged) where similarities is a list of
    SequenceMatcher ratios and flagged contains low-similarity entries.
    """
    similarities: list[float] = []
    flagged: list[dict] = []

    # Get all our vibe_summary and smol_summary entries
    our_summaries: dict[str, str] = {}
    for row in network_conn.execute(
        "SELECT model_id, value FROM model_metadata WHERE key IN ('vibe_summary', 'smol_summary')"
    ).fetchall():
        # Prefer smol_summary if both exist; last write wins in this iteration
        our_summaries[row[0]] = row[1]

    for model_id, gt_summary in gt_summaries.items():
        our_summary = our_summaries.get(model_id)
        if not our_summary:
            continue
        ratio = difflib.SequenceMatcher(
            None, our_summary.lower(), gt_summary.lower()
        ).ratio()
        similarities.append(ratio)
        if ratio < 0.2:
            flagged.append(
                {
                    "model_id": model_id,
                    "type": "low_summary_similarity",
                    "similarity": round(ratio, 3),
                    "ours": our_summary[:100],
                    "reference": gt_summary[:100],
                }
            )

    return similarities, flagged


def _expected_fields_from_parsed(parsed: dict) -> set[str]:
    """Extract expected anchor-related fields from a parsed model card."""
    fields: set[str] = set()
    base_model = parsed.get("base_model") or parsed.get("base_model_mention") or ""
    if base_model:
        fields.add("lineage")
    training = parsed.get("training_data") or parsed.get("datasets") or ""
    if training:
        fields.add("training-data")
    language = parsed.get("language") or ""
    if language:
        fields.add("multilingual" if "," in str(language) else "language")
    return fields


def _check_param_mismatch(
    network_conn: sqlite3.Connection,
    model_id: str,
    parsed: dict,
) -> dict | None:
    """Check if our parameter count disagrees with ground truth. Returns flag dict or None."""
    gt_params = parsed.get("parameters") or parsed.get("num_parameters")
    if not gt_params:
        return None
    our_params_row = network_conn.execute(
        "SELECT value FROM model_metadata WHERE model_id = ? AND key = 'parameter_count_b'",
        (model_id,),
    ).fetchone()
    if not our_params_row:
        return None
    try:
        our_val = float(our_params_row[0])
        gt_val = float(gt_params)
        # Normalize — gt might be raw count, ours is in billions
        if gt_val > 1e6:
            gt_val = gt_val / 1e9
        if abs(our_val - gt_val) / max(our_val, gt_val, 1e-9) > 0.5:
            return {
                "model_id": model_id,
                "type": "param_count_mismatch",
                "ours": our_val,
                "reference": gt_val,
            }
    except (ValueError, TypeError):
        pass
    return None


def _compare_parsed_cards(
    network_conn: sqlite3.Connection,
    gt_parsed: dict[str, dict],
) -> tuple[list[float], list[dict]]:
    """Compare our anchors against parsed model card ground truth.

    Returns (anchor_coverages, flagged).
    """
    anchor_coverages: list[float] = []
    flagged: list[dict] = []

    for model_id, parsed in gt_parsed.items():
        our_anchors = {
            row[0].lower()
            for row in network_conn.execute(
                """SELECT a.label FROM model_anchors ma
                   JOIN anchors a ON ma.anchor_id = a.anchor_id
                   WHERE ma.model_id = ?""",
                (model_id,),
            ).fetchall()
        }
        if not our_anchors:
            continue

        expected_fields = _expected_fields_from_parsed(parsed)
        if expected_fields:
            covered = sum(
                1 for f in expected_fields if any(f in a for a in our_anchors)
            )
            coverage = covered / len(expected_fields)
            anchor_coverages.append(coverage)

        mismatch = _check_param_mismatch(network_conn, model_id, parsed)
        if mismatch:
            flagged.append(mismatch)

    return anchor_coverages, flagged


def validate_against_ground_truth(
    network_conn: sqlite3.Connection,
    gt_summaries: dict[str, str],
    gt_parsed: dict[str, dict],
) -> dict:
    """Compare our outputs vs ground truth.

    Checks:
    - String similarity for summaries (difflib.SequenceMatcher)
    - Anchor coverage vs parsed_model_cards fields
    - Flag major disagreements (param count mismatch, wrong base model)

    Returns dict with metrics:
        total_compared: int
        summary_comparisons: int
        similarity_mean: float
        similarity_median: float
        parsed_comparisons: int
        anchor_coverage_mean: float
        flagged_disagreements: list[dict]
    """
    similarities, summary_flags = _compare_summaries(network_conn, gt_summaries)
    anchor_coverages, parsed_flags = _compare_parsed_cards(network_conn, gt_parsed)
    flagged = summary_flags + parsed_flags

    similarity_mean = sum(similarities) / len(similarities) if similarities else 0.0
    sorted_sims = sorted(similarities)
    similarity_median = sorted_sims[len(sorted_sims) // 2] if sorted_sims else 0.0
    anchor_coverage_mean = (
        sum(anchor_coverages) / len(anchor_coverages) if anchor_coverages else 0.0
    )
    total_compared = len(similarities) + len(anchor_coverages)

    logger.info(
        "Ground truth validation: %d compared, similarity=%.3f, coverage=%.3f, %d flagged",
        total_compared,
        similarity_mean,
        anchor_coverage_mean,
        len(flagged),
    )
    return {
        "total_compared": total_compared,
        "summary_comparisons": len(similarities),
        "similarity_mean": round(similarity_mean, 3),
        "similarity_median": round(similarity_median, 3),
        "parsed_comparisons": len(anchor_coverages),
        "anchor_coverage_mean": round(anchor_coverage_mean, 3),
        "flagged_disagreements": flagged,
    }
